MODEL:
  PIXEL_MEAN : [127.5, 127.5, 127.5]
  PIXEL_STD : [127.5, 127.5, 127.5]
  META_ARCHITECTURE: "SAM3MC_o365"
  SAM3:
    BPE_PATH: "sam3/assets/bpe_simple_vocab_16e6.txt.gz"
    ENABLE_SEGMENTATION: True
    NUM_CDT: 0

    USE_QUERY_PROJ: False
    USE_PE_TEXT: False
    USE_GATE: True
  WEIGHTS: "/data/hmp/sam3.pt"
  # WEIGHTS: "/root/hub_home/hub/models--facebook--sam3/snapshots/3c879f39826c281e95690f02c7821c4de09afae7/sam3.pt" 
  # WEIGHTS: /data/hmp/TASK/OVS/mysamMultiDateset/out/cocopano/box/model_0003749.pth

DATASETS:
  TRAIN: ("coco_2017_train_panoptic", "openvocab_coco_2017_train_stuff_sem_seg",)  
  TEST: ("openvocab_ade20k_panoptic_val",) 

  ONLY_INSTANCE: True

SOLVER:
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 12
  BASE_LR: 0.00005
  LR_SCHEDULER_NAME: WarmupPolyLR
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 5000
  
  # Loss 权重保持你原本的设置
  CLASS_WEIGHT: 2.0
  MASK_WEIGHT: 5.0
  DICE_WEIGHT: 5.0
  USE_AUX : True
  
  ENCODER_LOSS: FALSE

INPUT:
  DATASET_MAPPER_NAME: "coco_combine_lsj"
  IMAGE_SIZE: 1008
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  # 建议开启，学长的配置里有，对于 LSJ (Large Scale Jittering) 训练通常配套颜色增强
  COLOR_AUG_SSD: True 
  MASK_FORMAT: "bitmask" # 明确指定 mask 格式，防止二义性

# ============================================================
#新增的核心部分：支持多数据集混合训练的 Loader 配置
# ============================================================
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"

  DATASET_RATIO: [2.0, 1.0]

  DATASET_BS: [8, 8]
  
  # 针对长尾分布采样：Obj365开启(True)，COCO关闭(False)
  USE_RFS: [False, False]
  
  # 指定标注类型，用于计算采样频率
  DATASET_ANN: ['box', 'box']
  
  # 其他 Loader 参数
  NUM_WORKERS: 12
  FILTER_EMPTY_ANNOTATIONS: True
  ASPECT_RATIO_GROUPING: True
  USE_DIFF_BS_SIZE: True


TEST:
  EVAL_PERIOD: 5000
  INSTANCE_ON: True   
  PANOPTIC_ON: True   
  SEMANTIC_ON: True   

# OUTPUT_DIR: ./out/copastf/
OUTPUT_DIR: ./out/test
VERSION: 2